dataset_config:
  desc: Multilinuagal sentiment classification dataset
  test:
    dataset_path: tyqiangz/multilingual-sentiments
    dataset_language: "all" # all languages
    return_dict: true
    padding: longest
    max_length: 512
    sub_split_size: null

tokenizer_config:
  tokenizer_name: gpt2
  tokenizer_path: "openai-community/gpt2"

model_config:
  model_name: gpt2
  model_path: "/home/hmankodi/Projects/LlamaSentimentClassification/TrainingLogs/runs/gpt2_all/model"
  num_labels: 3
  # force_download: true
  # config goes here

prediction_config:
  samples:
    - what was the irony?
    - Gisburn was very curious
    # - Gisburn was very curious
    # - Mrs. Gisburn was wealthy
    # - I made a deprecating
